### PR TITLE
Add sharp quote advice (fixes #7).

### LINKED ISSUE #7: Proposal: prefer #' (sharp quote) when quoting function names
When quoting symbols to access their function definitions, prefer the use of sharp quotes. This allows the bytecompiler to check if the function exists, issuing a warning just like it would when calling an undefined function.

This would change the anonymous function example.

~~~el
(cl-remove-if-not #'evenp numbers)
~~~

Sharp quoting has become a lot more relevant with the introduction of lexical scoping.

~~~el
(defun foo ()
  :global)

(cl-flet ((foo () :local))
  (list (funcall 'foo) (funcall #'foo)))
;; => (:global :local)
~~~

### PR DESCRIPTION
**Pull request by skeeto**
Adds advice according to #7.

### CODE REVIEW

**Comment by bbatsov** [comment]
@skeeto Ping :-)

**Comment by dgutov** [comment]
I don't think we should list key bindings or hooks as exceptions.

AFAICS, sharp quotes have a consistent benefit (byte compiler warnings), and no real drawbacks in any usages. There are actually a lot of places of them being used in key binding forms inside Emacs core (roughly ~100 matches). The ones in `lisp/net/quickurl.el`, for example, were added originally in 1999 by RMS himself.

**Comment by bbatsov** [comment]
I totally agree.

On Sunday, January 25, 2015, Dmitry Gutov <notifications@github.com> wrote:

> I don't think we should list key bindings or hooks as exceptions.
>
> AFAICS, sharp quotes have a consistent benefit (byte compiler warnings),
> and no real drawbacks in any usages. There are actually a lot of places of
> them being used in key binding forms inside Emacs core (roughly ~100
> matches). The ones in lisp/net/quickurl.el, for example, were added
> originally in 1999 by RMS himself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bbatsov/emacs-lisp-style-guide/pull/12#issuecomment-71371627>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by lunaryorn** [comment]
So do I.  A function is a function, whether in a key binding or not.

**Comment by Bruce-Connor** [comment]
Me too. Despite my previous on-the-fence comment, I've since started using and recommending it unconditionally.

**Comment by bbatsov** [comment]
Guess @skeeto forgot about this PR, so one of us should probably commit the updated rule/examples.

**Comment by dgutov** [comment]
Done, kinda.

I'm not sure what to write about macros: the `cl-labels` example returns `(:local :local)` in the current Emacs master. Maybe it was just a long-standing bug, but either way it's there in 24.4 and earlier.

**Pull request closed without merging**
